### ISSUE TITLE
error: cannot find symbol import tv.teads.sdk.android.AdFailedReason;    after updating the teads SDK

### ISSUE THREAD

**Issue by jesphinpt** [teads/TeadsSDK-android#168]
After updating the teads SDK from 4.3.3@aar to 5.0.2 or to latest version, I am getting the below errors

```
 //Teads
 implementation("tv.teads.sdk.android:sdk:4.3.3@aar") {
 implementation("tv.teads.sdk.android:sdk:5.0.2@aar") {
         transitive = true
     }
```
```

error: cannot find symbol
import tv.teads.sdk.android.InReadAdView;
                           ^
  symbol:   class InReadAdView
  location: package tv.teads.sdk.android
error: cannot find symbol
import tv.teads.sdk.android.TeadsListener;
                           ^
  symbol:   class TeadsListener
  location: package tv.teads.sdk.android

error: cannot find symbol import tv.teads.sdk.android.AdFailedReason;     ^   symbol:   class AdFailedReason   location: package tv.teads.sdk.android

 error: cannot find symbol
                    super.onAdLoaded(v);
                         ^
  symbol: method onAdLoaded(float)

error: method does not override or implement a method from a supertype
                @Override
                ^
```
